version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    exclude-paths:
      - "test/**"
      - "examples/**"
      - "website/**"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      root-and-package-dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      website-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
