approvedGitRepositories:
  - "**"

catalog:
  "@vitest/coverage-v8": 4.1.5
  vitest: 4.1.5
  unbuild: 3.6.1

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

unsafeHttpWhitelist:
  - 0.0.0.0

yarnPath: .yarn/releases/yarn-4.14.1.cjs
