version: 2

aliases:
  - &attach-workspace
      at: build

  - &restore-cache
      key: node-modules-{{ checksum "yarn.lock" }}
  - &yarn-install
      name: Install dependencies
      command: yarn install --no-progress

jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *yarn-install

      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
              - node_modules

      - run: node scripts/build/

      - persist_to_workspace:
          root: build
          paths:
            - packages

  test-node-latest:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - attach-workspace: *attach-workspace
      - restore-cache: *restore-cache
      - run: *yarn-install

      - run:
          name: Install build tools
          command: sudo yarn global add codecov yalc

      - run: node scripts/test.js --skip-build

      - run:
          name: Send coverage report
          command: codecov

      - store_test_results:
          path: ./results/
          when: always

  test-node-8:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - attach-workspace: *attach-workspace
      - restore-cache: *restore-cache
      - run: *yarn-install

      - run:
          name: Install build tools
          command: sudo yarn global add codecov yalc

      - run: node scripts/test.js --skip-build

  publish:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - attach-workspace: *attach-workspace
      - restore-cache: *restore-cache
      - run: *yarn-install

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - run: node scripts/release/update-versions.js --next
      - run: node scripts/release/release-npm.js --next

  test-linter:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *yarn-install
      - run: yarn run lint

  build-docs:
    docker:
      - image: circleci/python:3.6
        environment:
          PYGMENTS_NODE_COMMAND: /usr/local/bin/node

    steps:
      - checkout

      - restore_cache:
          key: pipenv-{{ checksum "Pipfile.lock" }}

      - run: pipenv install

      - save_cache:
          key: pipenv-{{ checksum "Pipfile.lock" }}
          paths:
              - "{{ pipenv --venv }}"

      - run: cd docs; pipenv run make html

      - deploy:
          command: ./scripts/legacy/deploy-docs.sh

workflows:
  version: 2
  test_n_deploy:
    jobs:
      - build-docs:
          filters:
            branches:
              only:
                - master
                - stable-2.x

      - build

      - test-linter:
          requires:
            - build
      - test-node-latest:
          requires:
            - build
      - test-node-8:
          requires:
            - build

# Disable automatic publish, because NPM requires OTP token
#      - publish:
#          requires:
#            - test-linter
#            - test-node-latest
#            - test-node-8
#          filters:
#            branches:
#              only:
#                - master
#                - stable-2.x
