// flow-typed signature: fbcee2345c5487c20ef91f4185e6d5ad
// flow-typed version: <<STUB>>/babel-types_v6.24.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-types/lib/constants' {
  declare module.exports: any;
}

declare module 'babel-types/lib/converters' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/core' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/es2015' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/experimental' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/flow' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/index' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/init' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/jsx' {
  declare module.exports: any;
}

declare module 'babel-types/lib/definitions/misc' {
  declare module.exports: any;
}

declare module 'babel-types/lib/flow' {
  declare module.exports: any;
}

declare module 'babel-types/lib/index' {
  declare module.exports: any;
}

declare module 'babel-types/lib/react' {
  declare module.exports: any;
}

declare module 'babel-types/lib/retrievers' {
  declare module.exports: any;
}

declare module 'babel-types/lib/validators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-types/lib/constants.js' {
  declare module.exports: $Exports<'babel-types/lib/constants'>;
}
declare module 'babel-types/lib/converters.js' {
  declare module.exports: $Exports<'babel-types/lib/converters'>;
}
declare module 'babel-types/lib/definitions/core.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/core'>;
}
declare module 'babel-types/lib/definitions/es2015.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/es2015'>;
}
declare module 'babel-types/lib/definitions/experimental.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/experimental'>;
}
declare module 'babel-types/lib/definitions/flow.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/flow'>;
}
declare module 'babel-types/lib/definitions/index.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/index'>;
}
declare module 'babel-types/lib/definitions/init.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/init'>;
}
declare module 'babel-types/lib/definitions/jsx.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/jsx'>;
}
declare module 'babel-types/lib/definitions/misc.js' {
  declare module.exports: $Exports<'babel-types/lib/definitions/misc'>;
}
declare module 'babel-types/lib/flow.js' {
  declare module.exports: $Exports<'babel-types/lib/flow'>;
}
declare module 'babel-types/lib/index.js' {
  declare module.exports: $Exports<'babel-types/lib/index'>;
}
declare module 'babel-types/lib/react.js' {
  declare module.exports: $Exports<'babel-types/lib/react'>;
}
declare module 'babel-types/lib/retrievers.js' {
  declare module.exports: $Exports<'babel-types/lib/retrievers'>;
}
declare module 'babel-types/lib/validators.js' {
  declare module.exports: $Exports<'babel-types/lib/validators'>;
}
