// flow-typed signature: 35164c3570dbd56cee5165969f8161e3
// flow-typed version: <<STUB>>/babel-plugin-resolver_v^1.1.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-resolver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-resolver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-resolver/example-app/app' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/example-app/controllers/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/example-app/controllers/User' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/example-app/lib/relativeImport' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/example-app/lib/utils' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/example-app/models/User' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/lib/getAbsoluteDirsFromInputDirs' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/lib/getFilenameFromBabelOpts' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/lib/getPluginOptsFromBabelOpts' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/lib/ResolverPlugin' {
  declare module.exports: any;
}

declare module 'babel-plugin-resolver/test/babelPluginResolver.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-resolver/example-app/app.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/example-app/app'>;
}
declare module 'babel-plugin-resolver/example-app/controllers/index.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/example-app/controllers/index'>;
}
declare module 'babel-plugin-resolver/example-app/controllers/User.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/example-app/controllers/User'>;
}
declare module 'babel-plugin-resolver/example-app/lib/relativeImport.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/example-app/lib/relativeImport'>;
}
declare module 'babel-plugin-resolver/example-app/lib/utils.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/example-app/lib/utils'>;
}
declare module 'babel-plugin-resolver/example-app/models/User.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/example-app/models/User'>;
}
declare module 'babel-plugin-resolver/lib/getAbsoluteDirsFromInputDirs.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/lib/getAbsoluteDirsFromInputDirs'>;
}
declare module 'babel-plugin-resolver/lib/getFilenameFromBabelOpts.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/lib/getFilenameFromBabelOpts'>;
}
declare module 'babel-plugin-resolver/lib/getPluginOptsFromBabelOpts.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/lib/getPluginOptsFromBabelOpts'>;
}
declare module 'babel-plugin-resolver/lib/ResolverPlugin.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/lib/ResolverPlugin'>;
}
declare module 'babel-plugin-resolver/test/babelPluginResolver.test.js' {
  declare module.exports: $Exports<'babel-plugin-resolver/test/babelPluginResolver.test'>;
}
