// flow-typed signature: 82413ce8caadf0562e58a7e4c6fecd50
// flow-typed version: <<STUB>>/babel-plugin-syntax-jsx_v^6.18.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-syntax-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-syntax-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-syntax-jsx/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-syntax-jsx/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-syntax-jsx/lib/index'>;
}
