// flow-typed signature: b8099df95af3fc19911964d9200ccebb
// flow-typed version: <<STUB>>/cz-lerna-changelog_v^1.2.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-lerna-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-lerna-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cz-lerna-changelog/lib/autocomplete-questions' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/lib/index' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/lib/make-default-questions' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/src/autocomplete-questions' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/src/index' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/src/make-default-questions' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/test/_stub' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cz-lerna-changelog/lib/autocomplete-questions.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/lib/autocomplete-questions'>;
}
declare module 'cz-lerna-changelog/lib/index.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/lib/index'>;
}
declare module 'cz-lerna-changelog/lib/make-default-questions.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/lib/make-default-questions'>;
}
declare module 'cz-lerna-changelog/src/autocomplete-questions.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/src/autocomplete-questions'>;
}
declare module 'cz-lerna-changelog/src/index.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/src/index'>;
}
declare module 'cz-lerna-changelog/src/make-default-questions.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/src/make-default-questions'>;
}
declare module 'cz-lerna-changelog/test/_stub.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/test/_stub'>;
}
declare module 'cz-lerna-changelog/test/index.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/test/index'>;
}
