// flow-typed signature: cf398d1ce6dc87ae98872853516faf06
// flow-typed version: <<STUB>>/cz-lerna-changelog_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cz-lerna-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cz-lerna-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cz-lerna-changelog/lib/index' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/src/index' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/test/_stub' {
  declare module.exports: any;
}

declare module 'cz-lerna-changelog/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cz-lerna-changelog/lib/index.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/lib/index'>;
}
declare module 'cz-lerna-changelog/src/index.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/src/index'>;
}
declare module 'cz-lerna-changelog/test/_stub.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/test/_stub'>;
}
declare module 'cz-lerna-changelog/test/index.js' {
  declare module.exports: $Exports<'cz-lerna-changelog/test/index'>;
}
