// flow-typed signature: 94496738e753ea1c77dd3f4415cf304d
// flow-typed version: <<STUB>>/eslint-plugin-jest_v^21.2.0/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest/build/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/no_disabled_tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/no_focused_tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/no_identical_title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/build/rules/valid_expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jest/build/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/index'>;
}
declare module 'eslint-plugin-jest/build/rules/no_disabled_tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/no_disabled_tests'>;
}
declare module 'eslint-plugin-jest/build/rules/no_focused_tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/no_focused_tests'>;
}
declare module 'eslint-plugin-jest/build/rules/no_identical_title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/no_identical_title'>;
}
declare module 'eslint-plugin-jest/build/rules/types.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/types'>;
}
declare module 'eslint-plugin-jest/build/rules/valid_expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/build/rules/valid_expect'>;
}
