// flow-typed signature: af5a452e0b94acbe2f82c218af19dbc0
// flow-typed version: <<STUB>>/full-icu_v^1.2.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'full-icu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'full-icu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'full-icu/full-icu' {
  declare module.exports: any;
}

declare module 'full-icu/install-spawn' {
  declare module.exports: any;
}

declare module 'full-icu/node-icu-data' {
  declare module.exports: any;
}

declare module 'full-icu/postinstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'full-icu/full-icu.js' {
  declare module.exports: $Exports<'full-icu/full-icu'>;
}
declare module 'full-icu/install-spawn.js' {
  declare module.exports: $Exports<'full-icu/install-spawn'>;
}
declare module 'full-icu/node-icu-data.js' {
  declare module.exports: $Exports<'full-icu/node-icu-data'>;
}
declare module 'full-icu/postinstall.js' {
  declare module.exports: $Exports<'full-icu/postinstall'>;
}
