// flow-typed signature: 36ea3268d396a9deb63ef1c032d880ab
// flow-typed version: <<STUB>>/jasmine-reporters_v^2.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jasmine-reporters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jasmine-reporters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jasmine-reporters/bin/phantomjs-testrunner' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/spec/JUnitXmlReporterSpec' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/spec/NUnitXmlReporterSpec' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/spec/TeamCityReporterSpec' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/src/appveyor_reporter' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/src/junit_reporter' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/src/nunit_reporter' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/src/tap_reporter' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/src/teamcity_reporter' {
  declare module.exports: any;
}

declare module 'jasmine-reporters/src/terminal_reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jasmine-reporters/bin/phantomjs-testrunner.js' {
  declare module.exports: $Exports<'jasmine-reporters/bin/phantomjs-testrunner'>;
}
declare module 'jasmine-reporters/index' {
  declare module.exports: $Exports<'jasmine-reporters'>;
}
declare module 'jasmine-reporters/index.js' {
  declare module.exports: $Exports<'jasmine-reporters'>;
}
declare module 'jasmine-reporters/spec/JUnitXmlReporterSpec.js' {
  declare module.exports: $Exports<'jasmine-reporters/spec/JUnitXmlReporterSpec'>;
}
declare module 'jasmine-reporters/spec/NUnitXmlReporterSpec.js' {
  declare module.exports: $Exports<'jasmine-reporters/spec/NUnitXmlReporterSpec'>;
}
declare module 'jasmine-reporters/spec/TeamCityReporterSpec.js' {
  declare module.exports: $Exports<'jasmine-reporters/spec/TeamCityReporterSpec'>;
}
declare module 'jasmine-reporters/src/appveyor_reporter.js' {
  declare module.exports: $Exports<'jasmine-reporters/src/appveyor_reporter'>;
}
declare module 'jasmine-reporters/src/junit_reporter.js' {
  declare module.exports: $Exports<'jasmine-reporters/src/junit_reporter'>;
}
declare module 'jasmine-reporters/src/nunit_reporter.js' {
  declare module.exports: $Exports<'jasmine-reporters/src/nunit_reporter'>;
}
declare module 'jasmine-reporters/src/tap_reporter.js' {
  declare module.exports: $Exports<'jasmine-reporters/src/tap_reporter'>;
}
declare module 'jasmine-reporters/src/teamcity_reporter.js' {
  declare module.exports: $Exports<'jasmine-reporters/src/teamcity_reporter'>;
}
declare module 'jasmine-reporters/src/terminal_reporter.js' {
  declare module.exports: $Exports<'jasmine-reporters/src/terminal_reporter'>;
}
