// flow-typed signature: b0575fa25d4f010baf547606de15210c
// flow-typed version: <<STUB>>/jest-serializer-html_v^5.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-serializer-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-serializer-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jest-serializer-html/index' {
  declare module.exports: $Exports<'jest-serializer-html'>;
}
declare module 'jest-serializer-html/index.js' {
  declare module.exports: $Exports<'jest-serializer-html'>;
}
