// flow-typed signature: c45402457ff9b6e77d6c0f5156f66406
// flow-typed version: <<STUB>>/make-plural_v4.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'make-plural'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'make-plural' {
  declare module.exports: any;
}
