// flow-typed signature: b2a40ec104f4b26b86f3520224e12902
// flow-typed version: <<STUB>>/memory-fs_v^0.4.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memory-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memory-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memory-fs/lib/join' {
  declare module.exports: any;
}

declare module 'memory-fs/lib/MemoryFileSystem' {
  declare module.exports: any;
}

declare module 'memory-fs/lib/normalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memory-fs/lib/join.js' {
  declare module.exports: $Exports<'memory-fs/lib/join'>;
}
declare module 'memory-fs/lib/MemoryFileSystem.js' {
  declare module.exports: $Exports<'memory-fs/lib/MemoryFileSystem'>;
}
declare module 'memory-fs/lib/normalize.js' {
  declare module.exports: $Exports<'memory-fs/lib/normalize'>;
}
