// flow-typed signature: b86daf1a897ddeef8d4a243161a44a13
// flow-typed version: <<STUB>>/messageformat_v1.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'messageformat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'messageformat' {
  declare module.exports: any;
}
