// flow-typed signature: baa841d7dcbca36e4b8e15ad09b7a968
// flow-typed version: <<STUB>>/messageformat-parser_v1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'messageformat-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'messageformat-parser' {
  declare module.exports: any;
}
