// flow-typed signature: ae95414a6deda05927b80536148e042e
// flow-typed version: <<STUB>>/mock-fs_v^4.6.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-fs/lib/binding' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/buffer' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/descriptor' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/directory' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/error' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/file' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/filesystem' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/index' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/item' {
  declare module.exports: any;
}

declare module 'mock-fs/lib/symlink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-fs/lib/binding.js' {
  declare module.exports: $Exports<'mock-fs/lib/binding'>;
}
declare module 'mock-fs/lib/buffer.js' {
  declare module.exports: $Exports<'mock-fs/lib/buffer'>;
}
declare module 'mock-fs/lib/descriptor.js' {
  declare module.exports: $Exports<'mock-fs/lib/descriptor'>;
}
declare module 'mock-fs/lib/directory.js' {
  declare module.exports: $Exports<'mock-fs/lib/directory'>;
}
declare module 'mock-fs/lib/error.js' {
  declare module.exports: $Exports<'mock-fs/lib/error'>;
}
declare module 'mock-fs/lib/file.js' {
  declare module.exports: $Exports<'mock-fs/lib/file'>;
}
declare module 'mock-fs/lib/filesystem.js' {
  declare module.exports: $Exports<'mock-fs/lib/filesystem'>;
}
declare module 'mock-fs/lib/index.js' {
  declare module.exports: $Exports<'mock-fs/lib/index'>;
}
declare module 'mock-fs/lib/item.js' {
  declare module.exports: $Exports<'mock-fs/lib/item'>;
}
declare module 'mock-fs/lib/symlink.js' {
  declare module.exports: $Exports<'mock-fs/lib/symlink'>;
}
