// flow-typed signature: 2fef2b6cc95c46e055392503ce945613
// flow-typed version: <<STUB>>/ncp_v^2.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ncp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ncp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ncp/lib/ncp' {
  declare module.exports: any;
}

declare module 'ncp/test/ncp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ncp/lib/ncp.js' {
  declare module.exports: $Exports<'ncp/lib/ncp'>;
}
declare module 'ncp/test/ncp.js' {
  declare module.exports: $Exports<'ncp/test/ncp'>;
}
