// flow-typed signature: 0ed60a64cb2943b87ec1879799fd6356
// flow-typed version: <<STUB>>/nixt_v^0.5.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nixt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nixt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nixt/hydro.conf' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/batch' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/expectations' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/middlewares' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/plugin' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/respond' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/result' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/runner' {
  declare module.exports: any;
}

declare module 'nixt/lib/nixt/world' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nixt/hydro.conf.js' {
  declare module.exports: $Exports<'nixt/hydro.conf'>;
}
declare module 'nixt/index' {
  declare module.exports: $Exports<'nixt'>;
}
declare module 'nixt/index.js' {
  declare module.exports: $Exports<'nixt'>;
}
declare module 'nixt/lib/nixt.js' {
  declare module.exports: $Exports<'nixt/lib/nixt'>;
}
declare module 'nixt/lib/nixt/batch.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/batch'>;
}
declare module 'nixt/lib/nixt/expectations.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/expectations'>;
}
declare module 'nixt/lib/nixt/middlewares.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/middlewares'>;
}
declare module 'nixt/lib/nixt/plugin.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/plugin'>;
}
declare module 'nixt/lib/nixt/respond.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/respond'>;
}
declare module 'nixt/lib/nixt/result.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/result'>;
}
declare module 'nixt/lib/nixt/runner.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/runner'>;
}
declare module 'nixt/lib/nixt/world.js' {
  declare module.exports: $Exports<'nixt/lib/nixt/world'>;
}
