// flow-typed signature: 64735340800071708e626e4c0aba3fbc
// flow-typed version: <<STUB>>/rollup-plugin-closure-compiler_v^0.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-closure-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-closure-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-closure-compiler/test/fixtures/export-number' {
  declare module.exports: any;
}

declare module 'rollup-plugin-closure-compiler/test/fixtures/plain-file' {
  declare module.exports: any;
}

declare module 'rollup-plugin-closure-compiler/test/fixtures/source-map' {
  declare module.exports: any;
}

declare module 'rollup-plugin-closure-compiler/test/fixtures/unminified' {
  declare module.exports: any;
}

declare module 'rollup-plugin-closure-compiler/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-closure-compiler/index' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler'>;
}
declare module 'rollup-plugin-closure-compiler/index.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler'>;
}
declare module 'rollup-plugin-closure-compiler/test/fixtures/export-number.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler/test/fixtures/export-number'>;
}
declare module 'rollup-plugin-closure-compiler/test/fixtures/plain-file.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler/test/fixtures/plain-file'>;
}
declare module 'rollup-plugin-closure-compiler/test/fixtures/source-map.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler/test/fixtures/source-map'>;
}
declare module 'rollup-plugin-closure-compiler/test/fixtures/unminified.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler/test/fixtures/unminified'>;
}
declare module 'rollup-plugin-closure-compiler/test/test.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler/test/test'>;
}
