// flow-typed signature: 902e741244dc1fbc8b59c33835249d2d
// flow-typed version: <<STUB>>/rollup-plugin-closure-compiler-js_v^1.0.6/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-closure-compiler-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-closure-compiler-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-closure-compiler-js/dist/rollup-plugin-closure-compiler-js.es' {
  declare module.exports: any;
}

declare module 'rollup-plugin-closure-compiler-js/dist/rollup-plugin-closure-compiler-js' {
  declare module.exports: any;
}

declare module 'rollup-plugin-closure-compiler-js/src/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-closure-compiler-js/src/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-closure-compiler-js/dist/rollup-plugin-closure-compiler-js.es.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler-js/dist/rollup-plugin-closure-compiler-js.es'>;
}
declare module 'rollup-plugin-closure-compiler-js/dist/rollup-plugin-closure-compiler-js.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler-js/dist/rollup-plugin-closure-compiler-js'>;
}
declare module 'rollup-plugin-closure-compiler-js/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler-js/src/index'>;
}
declare module 'rollup-plugin-closure-compiler-js/src/logger.js' {
  declare module.exports: $Exports<'rollup-plugin-closure-compiler-js/src/logger'>;
}
