// flow-typed signature: a39d931e5998e86d2d035bc85eceb5eb
// flow-typed version: <<STUB>>/rollup-plugin-prettier_v^0.4.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-prettier/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-prettier/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-prettier/dist/index'>;
}
