// flow-typed signature: cce918b3b0d8c2997dfaafbc7d00f2a0
// flow-typed version: <<STUB>>/targz_v^1.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'targz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'targz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'targz/lib/targz' {
  declare module.exports: any;
}

// Filename aliases
declare module 'targz/index' {
  declare module.exports: $Exports<'targz'>;
}
declare module 'targz/index.js' {
  declare module.exports: $Exports<'targz'>;
}
declare module 'targz/lib/targz.js' {
  declare module.exports: $Exports<'targz/lib/targz'>;
}
