// flow-typed signature: f3cc4b313126832f983d88bc3a476b55
// flow-typed version: <<STUB>>/tmp_v^0.0.33/flow_v0.57.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tmp/lib/tmp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tmp/lib/tmp.js' {
  declare module.exports: $Exports<'tmp/lib/tmp'>;
}
