name: docs-suite

on:
  pull_request:
    branches:
      - '*'
    paths:
      - website/**

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        working-directory: website
        run: yarn install

      - name: Build
        working-directory: website
        run: yarn build

      - name: Lint
        working-directory: website
        run: yarn lint

      - name: Check Formatting
        working-directory: website
        run: yarn checkFormat
