name: Size Testing

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d # v1.8.0
        with:
          build_script: release:build
          github_token: ${{ secrets.GITHUB_TOKEN }}
