name: version-bump

on:
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: 'Version type to bump'
        options:
        - latest
        - next
        required: true
        default: "latest"

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
          scope: '@lingui'

      - name: Install dependencies if needed
        run: yarn install

      - name: Build packages
        run: yarn release:build

      - name: Unit Testing
        run: yarn test:ci

      - name: Linting & Types
        run: yarn lint:all

      - name: Prepare Lingui-Bot git account
        uses: oleksiyrudenko/gha-git-credentials@8bb1fe6d543b2233ef1856cd3b0181f5abbd4d6a # v2.1.2
        with:
          name: 'Lingui Bot'
          email: 'linguibot@gmail.com'
          actor: 'lingui-bot'
          token: '${{ secrets.GH_TOKEN }}'

      - name: Versioning packages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn version:${{github.event.inputs.versionType}}
